<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default2.aspx.cs" Inherits="Project.Default2" %>


<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
  
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="true" DataSourceID="SqlDataSource1" AutoGenerateColumns="False" DataKeyNames="id" AutoGenerateDeleteButton="true" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id"></asp:BoundField>
            <asp:BoundField DataField="ime" HeaderText="ime" SortExpression="ime"></asp:BoundField>
            <asp:BoundField DataField="prezime" HeaderText="prezime" SortExpression="prezime"></asp:BoundField>
            <asp:BoundField DataField="tehnologije" HeaderText="tehnologije" SortExpression="tehnologije"></asp:BoundField>
            <asp:BoundField DataField="nagrade" HeaderText="nagrade" SortExpression="nagrade"></asp:BoundField>
            <asp:BoundField DataField="zasluge" HeaderText="zasluge" SortExpression="zasluge"></asp:BoundField>
        </Columns>
    </asp:GridView>

    <asp:SqlDataSource runat="server" ID="SqlDataSource1" ConnectionString='<%$ ConnectionStrings:projectConnectionString %>' DeleteCommand="DELETE FROM [programer] WHERE [id] = @id" InsertCommand="INSERT INTO [programer] ([id], [ime], [prezime], [tehnologije], [nagrade], [zasluge]) VALUES (@id, @ime, @prezime, @tehnologije, @nagrade, @zasluge)" SelectCommand="SELECT * FROM [programer]" UpdateCommand="UPDATE [programer] SET [ime] = @ime, [prezime] = @prezime, [tehnologije] = @tehnologije, [nagrade] = @nagrade, [zasluge] = @zasluge WHERE [id] = @id">
        <DeleteParameters>
            <asp:Parameter Name="id" Type="String"></asp:Parameter>
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="id" Type="String"></asp:Parameter>
            <asp:Parameter Name="ime" Type="String"></asp:Parameter>
            <asp:Parameter Name="prezime" Type="String"></asp:Parameter>
            <asp:Parameter Name="tehnologije" Type="String"></asp:Parameter>
            <asp:Parameter Name="nagrade" Type="String"></asp:Parameter>
            <asp:Parameter Name="zasluge" Type="String"></asp:Parameter>
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="ime" Type="String"></asp:Parameter>
            <asp:Parameter Name="prezime" Type="String"></asp:Parameter>
            <asp:Parameter Name="tehnologije" Type="String"></asp:Parameter>
            <asp:Parameter Name="nagrade" Type="String"></asp:Parameter>
            <asp:Parameter Name="zasluge" Type="String"></asp:Parameter>
            <asp:Parameter Name="id" Type="String"></asp:Parameter>
        </UpdateParameters>
    </asp:SqlDataSource>

</asp:Content>